### ISSUE TITLE
Hola! 😄

### ISSUE THREAD

**Issue by TxusBlack** [JuanCaFelizzola/portafolio-desarrollo-web#1]
Hola! Me gustaría saber si la tienes en GitHub Pages y si tienes el enlace, me gustaría ver tu portafolio 👨🏻‍💻

**Comment by SidVal** [comment]
Llego tarde a este issue, pero recuerda que las GitHub Pages corren en subdominio compuesto con el nombre del repositorio y el autor del mismo.

En este caso, y espero que a @JuanCaFelizzola  no le moleste que divulgue la URL, es: 
https://juancafelizzola.github.io/portafolio-desarrollo-web/

**Comment by TxusBlack** [comment]
Graicas @SidVal ya pude verlo, está muy bueno @JuanCaFelizzola sigue así 😉

**Comment by TxusBlack** [comment]
Graicas @SidVal ya pude verlo, está muy bueno el portafolio @JuanCaFelizzola sigue así 👍🏻

**Comment by JuanCaDev** [comment]
Gracias @SidVal por responder.
Gracias @TxusBlack ya estoy intentando renovar y mejorar este.

**Comment by SidVal** [comment]
@TxusBlack ¿podes cerrar el issue así deja de salirme como issue abierto porfa? 🙏

**Comment by TxusBlack** [comment]
Hola @SidVal Claro! Ya lo cierro 😁
